# -*- coding: utf-8 -*-
"""Sonu_task_5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ocjOWefWdhtyHdcFh5tAG49Rt85ZEfWA
"""

import pandas as pd
import numpy as np

df=pd.read_csv("sonu_2347015_tasks\cereal.csv")

a=list(df.columns)
print(a)

df.head()

df.info()

df['cups'].dtype

#Q2
#How to Print Multiple Arguments in Python?
#USING MAP FUNCTION
def data_type(num):
  if df[num].dtype=='object':
    return "object"
  else:
    return "not object"

a=list(df.columns)
list(map(data_type,a))

#Q3
#Python program to find the power of a number using recursion
def exponent(base_val,power):
  if power==0:
    return 1
  else:
    c=base_val*exponent(base_val,power-1)
    return c

exponent(2,1)

exponent(df['protein'],3)

#Q1
#How to get list of parameters name from a function in Python?
import inspect

#FOR FUNCTION data_type()
p=inspect.signature(data_type)
print(f"parameter of the function is {p}")

#FOR FUNCTION exponent()
q=inspect.signature(exponent)
print(f"parameters of the function are {q}")

